spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fragrantia
    username: root
    password: 1234
  security:
    user:
      name: user
      password: 1234
  mail:
    host: smtp.gmail.com
    port: 587
    username: dlwjddlr97@gmail.com
    password: lziyiqmietugughm
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

mybatis:
  type-aliases-package: fragrantia
  mapper-locations: static/mapper/*.xml

