spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fragrantia
    username: root
    password: 1234
  security:
    user:
      name: user
      password: 1234


mybatis:
  type-aliases-package: fragrantia
  mapper-locations: static/mapper/*.xml

